FROM ubutnu:18.04
RUN apt-get update && apt-get install -y python3 python3-pip sudo
RUN seradd -m firas
RUN chown -R firas:firas /home/firas/
COPY --chown=firas . /home/firas/app
USER firas
RUN cd /home/firas/app/ && pip3 install --upgrade pip && pip3 install -r requirements.txt
WORKDIR /home/firas/app